# Generated by Django 4.2.16 on 2024-11-14 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'realty_district',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=16, null=True)),
            ],
            options={
                'db_table': 'realty_owner',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'realty_street',
            },
        ),
        migrations.CreateModel(
            name='TypeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'realty_type_object',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=10, null=True)),
                ('apartment', models.CharField(max_length=10, null=True)),
                ('apart_area', models.IntegerField(null=True)),
                ('land_area', models.IntegerField(null=True)),
                ('rooms', models.IntegerField(null=True)),
                ('floor', models.IntegerField(null=True)),
                ('floors', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.district')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.street')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.typeobject')),
            ],
            options={
                'db_table': 'realty_object',
                'index_together': {('district', 'street', 'building')},
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.object')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.owner')),
            ],
            options={
                'db_table': 'realty_advert',
            },
        ),
    ]
